import type { StepConfig } from '../flow/types'
import {
  anticoagulationOptions,
  bicarbonatePreparationOptions,
  calciumFluidTypeOptions,
  calciumGluconatePreparationOptions,
  citratePreparationOptions,
  fluidAllocationOptions,
  modeOptions,
  potassiumChloridePreparationOptions,
  potassiumContextOptions,
  replacementPositionOptions,
} from './options'

export const steps: StepConfig[] = [
  {
    id: 'basic',
    title: '基础信息',
    description: '先录入真正参与后续计算的最小基础参数。',
    fields: [
      {
        id: 'weight',
        label: '体重',
        type: 'number',
        unit: 'kg',
        placeholder: '例如 70',
        purpose: 'calculation',
      },
    ],
  },
  {
    id: 'therapy',
    title: '治疗设置',
    description: '已接入体重、目标治疗剂量与置换液/透析液流量计算。',
    fields: [
      {
        id: 'mode',
        label: 'CRRT / CBP 模式',
        type: 'single',
        allowOther: true,
        options: modeOptions,
        purpose: 'calculation',
      },
      {
        id: 'targetDose',
        label: '目标治疗剂量',
        type: 'number',
        unit: 'mL/kg/h',
        placeholder: '例如 25',
        helpText: '由临床医生设定目标剂量；计算器只负责换算，不自动替代临床判断。',
        purpose: 'calculation',
      },
      {
        id: 'bloodFlow',
        label: '血流量',
        type: 'number',
        unit: 'mL/min',
        placeholder: '例如 130',
        helpText: '枸橼酸初始泵速换算会使用该值。',
        purpose: 'calculation',
      },
      {
        id: 'netUf',
        label: '净超滤速度',
        type: 'number',
        unit: 'mL/h',
        placeholder: '例如 100；不脱水可填 0',
        helpText: '净超滤单独显示，并从目标总流出液量中单列。',
        purpose: 'calculation',
      },
      {
        id: 'fluidAllocation',
        label: '置换液 / 透析液分配方式',
        type: 'single',
        allowOther: true,
        options: fluidAllocationOptions,
        visibleIf: { field: 'mode', operator: 'equals', value: 'cvvhdf' },
        purpose: 'calculation',
      },
      {
        id: 'replacementShare',
        label: '置换液占比',
        type: 'number',
        unit: '%',
        placeholder: '例如 60',
        visibleIf: {
          operator: 'all',
          rules: [
            { field: 'mode', operator: 'equals', value: 'cvvhdf' },
            { field: 'fluidAllocation', operator: 'equals', value: 'custom_ratio' },
          ],
        },
        purpose: 'calculation',
      },
      {
        id: 'dialysateShare',
        label: '透析液占比',
        type: 'number',
        unit: '%',
        placeholder: '例如 40',
        visibleIf: {
          operator: 'all',
          rules: [
            { field: 'mode', operator: 'equals', value: 'cvvhdf' },
            { field: 'fluidAllocation', operator: 'equals', value: 'custom_ratio' },
          ],
        },
        purpose: 'calculation',
      },
      {
        id: 'replacementPosition',
        label: '置换液稀释方式',
        type: 'single',
        allowOther: true,
        options: replacementPositionOptions,
        visibleIf: { field: 'mode', operator: 'in', values: ['cvvh', 'cvvhdf'] },
        helpText: '记录前/后稀释方式；前稀释的有效清除校正后续再补。',
        purpose: 'context',
      },
    ],
  },
  {
    id: 'anticoagulation',
    title: '抗凝',
    description: '根据已选抗凝方式计算常用初始范围；最终剂量仍需结合监测动态调整。',
    fields: [
      {
        id: 'anticoagulation',
        label: '抗凝方式',
        type: 'single',
        allowOther: true,
        options: anticoagulationOptions,
        purpose: 'calculation',
      },
      {
        id: 'citratePreparation',
        label: '枸橼酸制剂',
        type: 'single',
        allowOther: true,
        options: citratePreparationOptions,
        visibleIf: { field: 'anticoagulation', operator: 'equals', value: 'citrate' },
        helpText: '2026版指南允许4%枸橼酸盐抗凝剂或0.5%枸橼酸盐置换液；当前自动换算先覆盖4%枸橼酸钠。',
        purpose: 'calculation',
      },
      {
        id: 'citrateCustomMmolL',
        label: '其他枸橼酸制剂浓度',
        type: 'number',
        unit: 'mmol/L',
        placeholder: '请输入枸橼酸根实际浓度',
        visibleIf: {
          operator: 'all',
          rules: [
            { field: 'anticoagulation', operator: 'equals', value: 'citrate' },
            { field: 'citratePreparation', operator: 'equals', value: '__other__' },
          ],
        },
        helpText: '为避免百分浓度与具体盐型换算混淆，自定义制剂直接录入枸橼酸根浓度。',
        purpose: 'calculation',
      },
      {
        id: 'citrateTarget',
        label: '目标体外血液枸橼酸浓度（可选）',
        type: 'number',
        unit: 'mmol/L',
        placeholder: '例如 3；留空则显示 3–4 mmol/L 对应泵速范围',
        visibleIf: {
          operator: 'all',
          rules: [
            { field: 'anticoagulation', operator: 'equals', value: 'citrate' },
            { field: 'citratePreparation', operator: 'in', values: ['trisodium_citrate_4pct', '__other__'] },
          ],
        },
        helpText: '该值用于计算初始泵速；治疗中应按滤器后离子钙动态调整。',
        purpose: 'calculation',
      },
      {
        id: 'heparinConcentration',
        label: '肝素配置浓度',
        type: 'number',
        unit: 'IU/mL',
        placeholder: '例如 500；不填仍可计算 IU 剂量范围',
        visibleIf: { field: 'anticoagulation', operator: 'equals', value: 'heparin' },
        helpText: '填写泵内实际浓度后，可把维持剂量进一步换算成 mL/h。',
        purpose: 'calculation',
      },
    ],
  },
  {
    id: 'electrolytes',
    title: '电解质 / 缓冲液',
    description: 'Phase 4：计算葡萄糖酸钙初始速度、NaHCO₃ 补碱泵速和 KCl 配液量；目标浓度仍由医生设定。',
    fields: [
      {
        id: 'calciumFluidType',
        label: 'RCA 处方液含钙情况',
        type: 'single',
        allowOther: true,
        options: calciumFluidTypeOptions,
        visibleIf: { field: 'anticoagulation', operator: 'equals', value: 'citrate' },
        helpText: '2026版指南允许 RCA 使用含钙或无钙置换液 / 透析液。',
        purpose: 'calculation',
      },
      {
        id: 'calciumGluconatePreparation',
        label: '补钙制剂',
        type: 'single',
        allowOther: true,
        options: calciumGluconatePreparationOptions,
        visibleIf: { field: 'anticoagulation', operator: 'equals', value: 'citrate' },
        helpText: '自动公式目前只覆盖指南明确给出的 10% 葡萄糖酸钙。',
        purpose: 'calculation',
      },
      {
        id: 'bicarbonatePreparation',
        label: 'NaHCO₃（碳酸氢钠）制剂',
        type: 'single',
        allowOther: true,
        options: bicarbonatePreparationOptions,
        purpose: 'calculation',
      },
      {
        id: 'bicarbonateCustomMmolMl',
        label: '其他 NaHCO₃ 实际浓度',
        type: 'number',
        unit: 'mmol/mL',
        placeholder: '请输入实际浓度',
        visibleIf: { field: 'bicarbonatePreparation', operator: 'equals', value: '__other__' },
        purpose: 'calculation',
      },
      {
        id: 'bicarbonateBaseMmolL',
        label: '基础处方液 HCO₃⁻ 浓度',
        type: 'number',
        unit: 'mmol/L',
        placeholder: '例如 0 或按成品液标签填写',
        helpText: '填写正在使用的基础置换液 / 透析液实际浓度。',
        purpose: 'calculation',
      },
      {
        id: 'bicarbonateTargetMmolL',
        label: '目标处方液 HCO₃⁻ 浓度',
        type: 'number',
        unit: 'mmol/L',
        placeholder: '由医生根据酸碱状态设定',
        helpText: '2026版指南没有规定所有患者统一目标值，因此不自动推荐一个固定数字。',
        purpose: 'calculation',
      },
      {
        id: 'bicarbonateCarrierFlowMlH',
        label: '需要补碱的基础处方液流量',
        type: 'number',
        unit: 'mL/h',
        placeholder: '填实际使用该基础液的流量',
        helpText: '只填需要通过该 NaHCO₃ 泵补碱的那部分处方液流量，不默认等于总流出液量。',
        purpose: 'calculation',
      },
      {
        id: 'potassiumContext',
        label: '当前钾管理情景',
        type: 'single',
        allowOther: true,
        options: potassiumContextOptions,
        helpText: '选择“高钾血症”后会按2026版指南检查目标处方液钾浓度是否在0–2 mmol/L范围。',
        purpose: 'context',
      },
      {
        id: 'potassiumChloridePreparation',
        label: 'KCl（氯化钾）制剂',
        type: 'single',
        allowOther: true,
        options: potassiumChloridePreparationOptions,
        purpose: 'calculation',
      },
      {
        id: 'potassiumCustomMmolMl',
        label: '其他 KCl 实际浓度',
        type: 'number',
        unit: 'mmol/mL',
        placeholder: '请输入实际浓度',
        visibleIf: { field: 'potassiumChloridePreparation', operator: 'equals', value: '__other__' },
        purpose: 'calculation',
      },
      {
        id: 'potassiumBaseMmolL',
        label: '基础处方液钾浓度',
        type: 'number',
        unit: 'mmol/L',
        placeholder: '例如 0',
        purpose: 'calculation',
      },
      {
        id: 'potassiumTargetMmolL',
        label: '目标处方液钾浓度',
        type: 'number',
        unit: 'mmol/L',
        placeholder: '由医生根据实时血钾设定',
        purpose: 'calculation',
      },
      {
        id: 'potassiumBagVolumeL',
        label: '单袋基础处方液体积',
        type: 'number',
        unit: 'L',
        placeholder: '例如 4',
        purpose: 'calculation',
      },
    ],
  },
]
