import type { StepConfig } from '../flow/types'
import {
  anticoagulationOptions,
  bicarbonatePreparationOptions,
  calciumGluconatePreparationOptions,
  citratePreparationOptions,
  fluidAllocationOptions,
  modeOptions,
  potassiumChloridePreparationOptions,
} from './options'

export const steps: StepConfig[] = [
  {
    id: 'basic',
    title: '基础信息',
    description: '先录入真正参与后续计算的最小基础参数。',
    fields: [
      {
        id: 'weight',
        label: '体重',
        type: 'number',
        unit: 'kg',
        placeholder: '例如 70',
        purpose: 'calculation',
      },
    ],
  },
  {
    id: 'therapy',
    title: '治疗设置',
    description: '这一页只收拢治疗模式、目标剂量、血流量和液体分配方式；具体公式在 Phase 2 接入。',
    fields: [
      {
        id: 'mode',
        label: 'CRRT / CBP 模式',
        type: 'single',
        allowOther: true,
        options: modeOptions,
        purpose: 'calculation',
      },
      {
        id: 'targetDose',
        label: '目标治疗剂量',
        type: 'number',
        unit: 'mL/kg/h',
        placeholder: '例如 25',
        helpText: 'Phase 1 仅记录输入，暂不自动推荐目标剂量。',
        purpose: 'calculation',
      },
      {
        id: 'bloodFlow',
        label: '血流量',
        type: 'number',
        unit: 'mL/min',
        placeholder: '例如 130',
        purpose: 'calculation',
      },
      {
        id: 'fluidAllocation',
        label: '置换液 / 透析液分配方式',
        type: 'single',
        allowOther: true,
        options: fluidAllocationOptions,
        purpose: 'calculation',
      },
      {
        id: 'replacementShare',
        label: '置换液占比',
        type: 'number',
        unit: '%',
        placeholder: '例如 60',
        visibleIf: { field: 'fluidAllocation', operator: 'equals', value: 'custom_ratio' },
        purpose: 'calculation',
      },
      {
        id: 'dialysateShare',
        label: '透析液占比',
        type: 'number',
        unit: '%',
        placeholder: '例如 40',
        visibleIf: { field: 'fluidAllocation', operator: 'equals', value: 'custom_ratio' },
        purpose: 'calculation',
      },
    ],
  },
  {
    id: 'anticoagulation',
    title: '抗凝',
    description: '选择抗凝路径后，只展开该路径后续计算需要的制剂输入。',
    fields: [
      {
        id: 'anticoagulation',
        label: '抗凝方式',
        type: 'single',
        allowOther: true,
        options: anticoagulationOptions,
        purpose: 'calculation',
      },
      {
        id: 'citratePreparation',
        label: '枸橼酸制剂',
        type: 'single',
        allowOther: true,
        options: citratePreparationOptions,
        visibleIf: { field: 'anticoagulation', operator: 'equals', value: 'citrate' },
        purpose: 'calculation',
      },
      {
        id: 'citrateCustomConcentration',
        label: '其他枸橼酸浓度',
        type: 'number',
        unit: '%',
        placeholder: '请输入实际规格',
        visibleIf: { field: 'citratePreparation', operator: 'equals', value: '__other__' },
        purpose: 'calculation',
      },
      {
        id: 'heparinConcentration',
        label: '肝素配置浓度',
        type: 'number',
        unit: 'IU/mL',
        placeholder: '输入实际泵内浓度',
        visibleIf: { field: 'anticoagulation', operator: 'equals', value: 'heparin' },
        purpose: 'calculation',
      },
    ],
  },
  {
    id: 'preparations',
    title: '制剂规格',
    description: '先把后续公式需要的制剂规格结构化。常用规格作为选项，院内其他规格可自由输入。',
    fields: [
      {
        id: 'calciumGluconatePreparation',
        label: '葡萄糖酸钙',
        type: 'single',
        allowOther: true,
        options: calciumGluconatePreparationOptions,
        visibleIf: { field: 'anticoagulation', operator: 'equals', value: 'citrate' },
        purpose: 'calculation',
      },
      {
        id: 'calciumGluconateCustomConcentration',
        label: '其他葡萄糖酸钙浓度',
        type: 'number',
        unit: '%',
        placeholder: '请输入实际规格',
        visibleIf: { field: 'calciumGluconatePreparation', operator: 'equals', value: '__other__' },
        purpose: 'calculation',
      },
      {
        id: 'bicarbonatePreparation',
        label: 'NaHCO₃（碳酸氢钠）',
        type: 'single',
        allowOther: true,
        options: bicarbonatePreparationOptions,
        purpose: 'calculation',
      },
      {
        id: 'bicarbonateCustomConcentration',
        label: '其他 NaHCO₃ 浓度',
        type: 'number',
        unit: '%',
        placeholder: '请输入实际规格',
        visibleIf: { field: 'bicarbonatePreparation', operator: 'equals', value: '__other__' },
        purpose: 'calculation',
      },
      {
        id: 'potassiumChloridePreparation',
        label: 'KCl（氯化钾）',
        type: 'single',
        allowOther: true,
        options: potassiumChloridePreparationOptions,
        purpose: 'calculation',
      },
      {
        id: 'potassiumChlorideCustomConcentration',
        label: '其他 KCl 浓度',
        type: 'number',
        unit: '%',
        placeholder: '请输入实际规格',
        visibleIf: { field: 'potassiumChloridePreparation', operator: 'equals', value: '__other__' },
        purpose: 'calculation',
      },
    ],
  },
]
